services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    container_name: backend
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - FRONTEND_HOST=${FRONTEND_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ACCESS_TOKEN_EXP_MIN=${ACCESS_TOKEN_EXP_MIN}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_EXP_DAYS=${REFRESH_TOKEN_EXP_DAYS}
      - CLIENT_ID=${CLIENT_ID}
      - REDIRECT_URL=${REDIRECT_URL_PROD}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ./backend/db:/db
      - /app/node_modules
      - uploads:/app/uploads
    restart: unless-stopped
    networks:
      - net

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      # - "443:443"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    expose:
      - "8888"
    depends_on:
      - backend
    volumes:
      - uploads:/uploads:ro
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  uploads:

